#!/bin/sh
set -e

# Replace build-time hardcoded variables.
echo "Replacing build-time variables."
grep -rl 'pk_test_JA==' .next | xargs sed -i 's/pk_test_JA==/'"$CLERK_PUBLISHABLE_KEY"'/g'
grep -rl 'PLACEHOLDER_NEXT_PUBLIC_CLERK_SIGN_IN_URL' .next | xargs sed -i 's@PLACEHOLDER_NEXT_PUBLIC_CLERK_SIGN_IN_URL@'"$CLERK_SIGN_IN_URL"'@g'
grep -rl 'PLACEHOLDER_NEXT_PUBLIC_CLERK_SIGN_IN_FALLBACK_REDIRECT_URL' .next | xargs sed -i 's@PLACEHOLDER_NEXT_PUBLIC_CLERK_SIGN_IN_FALLBACK_REDIRECT_URL@'"$CLERK_SIGN_IN_FALLBACK_REDIRECT_URL"'@g'
grep -rl 'PLACEHOLDER_NEXT_PUBLIC_DEFAULT_ORG_ID' .next | xargs sed -i 's/PLACEHOLDER_NEXT_PUBLIC_DEFAULT_ORG_ID/'"$DEFAULT_ORG_ID"'/g'

# Pass environment variables to node process. This should be moved to a loader within the app instead.
echo "Starting server."
DB_HOST=$DB_HOST DB_SOCKET_PATH=$DB_SOCKET_PATH DB_NAME=$DB_NAME DB_USER=$DB_USER DB_PASSWORD=$DB_PASSWORD \
  ENVIRONMENT=$ENVIRONMENT \
  CAREPOYNT_API_HOST=$CAREPOYNT_API_HOST \
  DATADOG_ENVIRONMENT=$DATADOG_ENVIRONMENT \
  DATADOG_API_KEY=$DATADOG_API_KEY DATADOG_APP_KEY=$DATADOG_APP_KEY \
  CLERK_SECRET_KEY=$CLERK_SECRET_KEY \
  BIGQUERY_PROJECT_ID=$BIGQUERY_PROJECT_ID BIGQUERY_LOCATION=$BIGQUERY_LOCATION \
  LOG_LEVEL=$LOG_LEVEL \
  TANGO_PLATFORM_NAME=$TANGO_PLATFORM_NAME \
  TANGO_API_KEY=$TANGO_API_KEY \
  exec "$@"
